### PR TITLE
Update to Bootstrap 4

### PR DESCRIPTION
**Pull request by prateekiiest**

### CODE REVIEW

**Comment by prateekiiest** [comment]
@championswimmer  @omerjerk ,
pls review this. if I am going the right way

Some files remain editing

**Comment by championswimmer** [comment]
In the JS file there is only version changed. The rest of the contents ?

**Comment by prateekiiest** [comment]
I would be updating that soon

**Comment by championswimmer** [comment]
what exactly do you want me to review ? you just copy pasted Bootstrap 4 code from the bootstrap cdn.
am I supposed to review how Twitter employees write bootstrap code? That's kinda above my paygrade. 

Just put all the required files, and we'll merge that. 
And don't use Github to make changes. Make the effort. Clone the repository. Make all the changes in a single commit.

**Pull request closed without merging**
