### PR TITLE
packaging added

### PR DESCRIPTION
**Pull request by akansh97531**
@piyush0 
run npm install at least once ,
run npm install --dev to ensure devdependencies are installed
then run npm package-win,
at last run npm run create-installer-win
and setup will be generated in installers folder (Snipper-setup-main.msi)
also changed electron builder version , it was giving some error in windows #15

### CODE REVIEW

**Comment by championswimmer** [comment]
can you upload a windows installer created from this ? I can try it out on Windows, if it works, we'll go ahead and merge this

**Comment by akansh97531** [comment]
@championswimmer please review
https://drive.google.com/open?id=0B01IghR9fsf-RGNsWmhsckNZTU0

**Comment by akansh97531** [comment]
travis configuration added @championswimmer

**Comment by akansh97531** [comment]
travis configuration added @championswimmer @piyush0

**Comment by akansh97531** [comment]
travis configuration added @championswimmer @piyush0

**Comment by championswimmer** [comment]
assigned you bounty for this directly here. you can claim

**Comment by akansh97531** [comment]
@championswimmer should i claim for 200+500 or only 500

**Comment by championswimmer** [comment]
claim 200 + 500

**Pull request merged**
