### PR TITLE
hotkey feature

### PR DESCRIPTION
**Pull request by akansh97531**
@piyush0 review

### CODE REVIEW

**Comment by akansh97531** [comment]
@piyush0 please take a look on feature added

**Comment by piyush0** [comment]
1) Hotkey doesn't do anything. Make it copy the code to clipboard
2) Incorrect format of hotkeys produces an error. Handle it with a toast

**Comment by akansh97531** [comment]
hotkey does copy the clip to clipboard please use the valid hotkey,
 and i will look for the 2nd point

**Comment by akansh97531** [comment]
@piyush0 i have added toaster for invalid key

**Comment by piyush0** [comment]
Awesome work!

**Comment by akansh97531** [comment]
thanks

**Pull request merged**
